table top_dst_2021_2025
	lineageTag: 1a3d2cd9-eb91-499c-8d7c-9cd9b826b472

	column team
		dataType: string
		lineageTag: 473c6db6-9c56-4127-9e74-25873cb649f1
		summarizeBy: none
		sourceColumn: team

		annotation SummarizationSetBy = Automatic

	column season
		dataType: int64
		formatString: 0
		lineageTag: 1f30e38e-0da9-4646-a9c4-779122532655
		summarizeBy: sum
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	column position
		dataType: string
		lineageTag: f9125351-2b4f-45b8-85b0-a1c3db175c69
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column ppr_avg
		dataType: int64
		formatString: 0
		lineageTag: 93879488-9f82-4890-829f-3cf606bba374
		summarizeBy: sum
		sourceColumn: ppr_avg

		annotation SummarizationSetBy = Automatic

	column points_allowed_avg
		dataType: int64
		formatString: 0
		lineageTag: 473b79ea-540c-43c3-a57a-3ae2acdd255f
		summarizeBy: sum
		sourceColumn: points_allowed_avg

		annotation SummarizationSetBy = Automatic

	column games
		dataType: int64
		formatString: 0
		lineageTag: 344149fc-8c07-4483-8803-2945add17cf5
		summarizeBy: sum
		sourceColumn: games

		annotation SummarizationSetBy = Automatic

	partition top_dst_2021_2025 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Projects\FantasyFootball\powerbi\inputs\top_dst_2021_2025.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"team", type text}, {"season", Int64.Type}, {"position", type text}, {"ppr_avg", Int64.Type}, {"points_allowed_avg", Int64.Type}, {"games", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

